//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Rent
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Bicycle.
    /// </summary>
    // *** Start programmer edit section *** (Bicycle CustomAttributes)

    // *** End programmer edit section *** (Bicycle CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class Bicycle : ICSSoft.STORMNET.DataObject
    {
        
        private string fIdentifier;
        
        private IIS.Rent.BicycleBrand fBrand;
        
        // *** Start programmer edit section *** (Bicycle CustomMembers)

        // *** End programmer edit section *** (Bicycle CustomMembers)

        
        /// <summary>
        /// Identifier.
        /// </summary>
        // *** Start programmer edit section *** (Bicycle.Identifier CustomAttributes)

        // *** End programmer edit section *** (Bicycle.Identifier CustomAttributes)
        [StrLen(255)]
        public virtual string Identifier
        {
            get
            {
                // *** Start programmer edit section *** (Bicycle.Identifier Get start)

                // *** End programmer edit section *** (Bicycle.Identifier Get start)
                string result = this.fIdentifier;
                // *** Start programmer edit section *** (Bicycle.Identifier Get end)

                // *** End programmer edit section *** (Bicycle.Identifier Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Bicycle.Identifier Set start)

                // *** End programmer edit section *** (Bicycle.Identifier Set start)
                this.fIdentifier = value;
                // *** Start programmer edit section *** (Bicycle.Identifier Set end)

                // *** End programmer edit section *** (Bicycle.Identifier Set end)
            }
        }
        
        /// <summary>
        /// Bicycle.
        /// </summary>
        // *** Start programmer edit section *** (Bicycle.Brand CustomAttributes)

        // *** End programmer edit section *** (Bicycle.Brand CustomAttributes)
        [NotNull()]
        public virtual IIS.Rent.BicycleBrand Brand
        {
            get
            {
                // *** Start programmer edit section *** (Bicycle.Brand Get start)

                // *** End programmer edit section *** (Bicycle.Brand Get start)
                IIS.Rent.BicycleBrand result = this.fBrand;
                // *** Start programmer edit section *** (Bicycle.Brand Get end)

                // *** End programmer edit section *** (Bicycle.Brand Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Bicycle.Brand Set start)

                // *** End programmer edit section *** (Bicycle.Brand Set start)
                this.fBrand = value;
                // *** Start programmer edit section *** (Bicycle.Brand Set end)

                // *** End programmer edit section *** (Bicycle.Brand Set end)
            }
        }
    }
}
