//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Rent
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// BiycleRent.
    /// </summary>
    // *** Start programmer edit section *** (BiycleRent CustomAttributes)

    // *** End programmer edit section *** (BiycleRent CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class BiycleRent : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fStartOfRent;
        
        private double fDuration;
        
        private System.DateTime fEndOfRent;
        
        private IIS.Rent.RentalPoint fGetAt;
        
        private IIS.Rent.RentalPoint fLeftAt;
        
        private IIS.Rent.Bicycle fRentedBicycle;
        
        // *** Start programmer edit section *** (BiycleRent CustomMembers)

        // *** End programmer edit section *** (BiycleRent CustomMembers)

        
        /// <summary>
        /// StartOfRent.
        /// </summary>
        // *** Start programmer edit section *** (BiycleRent.StartOfRent CustomAttributes)

        // *** End programmer edit section *** (BiycleRent.StartOfRent CustomAttributes)
        public virtual System.DateTime StartOfRent
        {
            get
            {
                // *** Start programmer edit section *** (BiycleRent.StartOfRent Get start)

                // *** End programmer edit section *** (BiycleRent.StartOfRent Get start)
                System.DateTime result = this.fStartOfRent;
                // *** Start programmer edit section *** (BiycleRent.StartOfRent Get end)

                // *** End programmer edit section *** (BiycleRent.StartOfRent Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BiycleRent.StartOfRent Set start)

                // *** End programmer edit section *** (BiycleRent.StartOfRent Set start)
                this.fStartOfRent = value;
                // *** Start programmer edit section *** (BiycleRent.StartOfRent Set end)

                // *** End programmer edit section *** (BiycleRent.StartOfRent Set end)
            }
        }
        
        /// <summary>
        /// Duration.
        /// </summary>
        // *** Start programmer edit section *** (BiycleRent.Duration CustomAttributes)

        // *** End programmer edit section *** (BiycleRent.Duration CustomAttributes)
        public virtual double Duration
        {
            get
            {
                // *** Start programmer edit section *** (BiycleRent.Duration Get start)

                // *** End programmer edit section *** (BiycleRent.Duration Get start)
                double result = this.fDuration;
                // *** Start programmer edit section *** (BiycleRent.Duration Get end)

                // *** End programmer edit section *** (BiycleRent.Duration Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BiycleRent.Duration Set start)

                // *** End programmer edit section *** (BiycleRent.Duration Set start)
                this.fDuration = value;
                // *** Start programmer edit section *** (BiycleRent.Duration Set end)

                // *** End programmer edit section *** (BiycleRent.Duration Set end)
            }
        }
        
        /// <summary>
        /// EndOfRent.
        /// </summary>
        // *** Start programmer edit section *** (BiycleRent.EndOfRent CustomAttributes)

        // *** End programmer edit section *** (BiycleRent.EndOfRent CustomAttributes)
        public virtual System.DateTime EndOfRent
        {
            get
            {
                // *** Start programmer edit section *** (BiycleRent.EndOfRent Get start)

                // *** End programmer edit section *** (BiycleRent.EndOfRent Get start)
                System.DateTime result = this.fEndOfRent;
                // *** Start programmer edit section *** (BiycleRent.EndOfRent Get end)

                // *** End programmer edit section *** (BiycleRent.EndOfRent Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BiycleRent.EndOfRent Set start)

                // *** End programmer edit section *** (BiycleRent.EndOfRent Set start)
                this.fEndOfRent = value;
                // *** Start programmer edit section *** (BiycleRent.EndOfRent Set end)

                // *** End programmer edit section *** (BiycleRent.EndOfRent Set end)
            }
        }
        
        /// <summary>
        /// BiycleRent.
        /// </summary>
        // *** Start programmer edit section *** (BiycleRent.GetAt CustomAttributes)

        // *** End programmer edit section *** (BiycleRent.GetAt CustomAttributes)
        [NotNull()]
        public virtual IIS.Rent.RentalPoint GetAt
        {
            get
            {
                // *** Start programmer edit section *** (BiycleRent.GetAt Get start)

                // *** End programmer edit section *** (BiycleRent.GetAt Get start)
                IIS.Rent.RentalPoint result = this.fGetAt;
                // *** Start programmer edit section *** (BiycleRent.GetAt Get end)

                // *** End programmer edit section *** (BiycleRent.GetAt Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BiycleRent.GetAt Set start)

                // *** End programmer edit section *** (BiycleRent.GetAt Set start)
                this.fGetAt = value;
                // *** Start programmer edit section *** (BiycleRent.GetAt Set end)

                // *** End programmer edit section *** (BiycleRent.GetAt Set end)
            }
        }
        
        /// <summary>
        /// BiycleRent.
        /// </summary>
        // *** Start programmer edit section *** (BiycleRent.LeftAt CustomAttributes)

        // *** End programmer edit section *** (BiycleRent.LeftAt CustomAttributes)
        [NotNull()]
        public virtual IIS.Rent.RentalPoint LeftAt
        {
            get
            {
                // *** Start programmer edit section *** (BiycleRent.LeftAt Get start)

                // *** End programmer edit section *** (BiycleRent.LeftAt Get start)
                IIS.Rent.RentalPoint result = this.fLeftAt;
                // *** Start programmer edit section *** (BiycleRent.LeftAt Get end)

                // *** End programmer edit section *** (BiycleRent.LeftAt Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BiycleRent.LeftAt Set start)

                // *** End programmer edit section *** (BiycleRent.LeftAt Set start)
                this.fLeftAt = value;
                // *** Start programmer edit section *** (BiycleRent.LeftAt Set end)

                // *** End programmer edit section *** (BiycleRent.LeftAt Set end)
            }
        }
        
        /// <summary>
        /// BiycleRent.
        /// </summary>
        // *** Start programmer edit section *** (BiycleRent.RentedBicycle CustomAttributes)

        // *** End programmer edit section *** (BiycleRent.RentedBicycle CustomAttributes)
        [NotNull()]
        public virtual IIS.Rent.Bicycle RentedBicycle
        {
            get
            {
                // *** Start programmer edit section *** (BiycleRent.RentedBicycle Get start)

                // *** End programmer edit section *** (BiycleRent.RentedBicycle Get start)
                IIS.Rent.Bicycle result = this.fRentedBicycle;
                // *** Start programmer edit section *** (BiycleRent.RentedBicycle Get end)

                // *** End programmer edit section *** (BiycleRent.RentedBicycle Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BiycleRent.RentedBicycle Set start)

                // *** End programmer edit section *** (BiycleRent.RentedBicycle Set start)
                this.fRentedBicycle = value;
                // *** Start programmer edit section *** (BiycleRent.RentedBicycle Set end)

                // *** End programmer edit section *** (BiycleRent.RentedBicycle Set end)
            }
        }
    }
}
