//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Rent
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// RentalPoint.
    /// </summary>
    // *** Start programmer edit section *** (RentalPoint CustomAttributes)

    // *** End programmer edit section *** (RentalPoint CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class RentalPoint : ICSSoft.STORMNET.DataObject
    {
        
        private string fAddress;
        
        // *** Start programmer edit section *** (RentalPoint CustomMembers)

        // *** End programmer edit section *** (RentalPoint CustomMembers)

        
        /// <summary>
        /// Address.
        /// </summary>
        // *** Start programmer edit section *** (RentalPoint.Address CustomAttributes)

        // *** End programmer edit section *** (RentalPoint.Address CustomAttributes)
        [StrLen(255)]
        public virtual string Address
        {
            get
            {
                // *** Start programmer edit section *** (RentalPoint.Address Get start)

                // *** End programmer edit section *** (RentalPoint.Address Get start)
                string result = this.fAddress;
                // *** Start programmer edit section *** (RentalPoint.Address Get end)

                // *** End programmer edit section *** (RentalPoint.Address Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (RentalPoint.Address Set start)

                // *** End programmer edit section *** (RentalPoint.Address Set start)
                this.fAddress = value;
                // *** Start programmer edit section *** (RentalPoint.Address Set end)

                // *** End programmer edit section *** (RentalPoint.Address Set end)
            }
        }
    }
}
